### ISSUE TITLE
[LinesCounter] Поддиректории

### ISSUE THREAD

**Issue by pavel-b-novikov** [kotnor/nsudotnet#1]
А где же обход файлов в поддиректориях?
И да. Сделайте, пожалуйста, не рекурсией, а нормальный обход стеком/деревом.

**Comment by kotnor** [comment]
Обход в поддиректориях присутствует)

**Comment by pavel-b-novikov** [comment]
А, да. Слона-то я и не приметил.

**Comment by pavel-b-novikov** [comment]
Задача принята, 2 балла.
