### ISSUE TITLE
[NumberGuesser] Конкатенация

### ISSUE THREAD

**Issue by pavel-b-novikov** [kotnor/nsudotnet#3]
> Console.WriteLine(_login + _myExpression[rnd.Next(0, 4)])

То есть сконфигурировать вашу программу так, чтобы имя пользователя выводилось в середине таунт-фразы невозможно?

**Comment by kotnor** [comment]
Как насчет такого? Console.WriteLine(string.Format(_myExpression[rnd.Next(0, 4)], _login));

**Comment by pavel-b-novikov** [comment]
Другое дело.
