### ISSUE TITLE
[Enigma] Using

### ISSUE THREAD

**Issue by pavel-b-novikov** [kotnor/nsudotnet#4]
```C#
using (var keyWriter = new StreamWriter(new FileStream(keys, FileMode.OpenOrCreate, FileAccess.Write)))
{
      //...
}
```

Нет, такой юзинг не будет работать как ожидалось. Переделайте нормально и объясните свою ошибку.

**Comment by kotnor** [comment]
Предполагаю, что в таком случае не вызовется Dispode для FileStream

**Comment by pavel-b-novikov** [comment]
Правильно предполагаете.
