### ISSUE TITLE
[Enigma] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [kotnor/nsudotnet#5]
Вы явно диспозите не все, что можно явно задиспозить.
Удивительно, но эта ошибка почему-то есть у ВСЕХ студентов, которые пишут Энигму и я даже как-то не обращал на неё раньше внимание.
Найдите что еще не убивается и насыпьте еще юзингов.

**Comment by kotnor** [comment]
Исправлено

**Comment by pavel-b-novikov** [comment]
Данке.
